Entretenimiento/alansalud
Atapiave/QA_team pull request #14
Opened 2022-03-10 23:04 UTC by AlanJoseph31

## Any background context you want to provide?
Music test cases were added, to perform validations from the dahsboard

## What does this PR do?
Perform music validation on the dashboard

## Where should the reviewer start?
must be started from the dashboard "Diversión"

## How should this be tested?

## What are the relevant tickets?

## Screenshots - Before

## Screenshots - After

## Questions :question:
#### Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2022-03-15 16:49 UTC, Atapiave requested changes
Also why are we naming the feature as musica.sec.feature?

2022-03-15 16:49 UTC, Atapiave commented on features/Entretenimiento /musica.sec.feature
> +    Scenario: 9_ ijdoiajsidas
What is this? 😅

2022-03-15 16:53 UTC, AlanJoseph31 commented on features/Entretenimiento /musica.sec.feature
> +    Scenario: 9_ ijdoiajsidas
lo siento, jajaa no cambie el nombre correcto!

2022-03-30 00:34 UTC, zoam21 requested changes

2022-03-30 00:34 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        Given to have the screens of the music section, it should show three playlists randomly, with image and genre.
El nombre de la sección lo pondría entre comillas y en español, para que sea más fácil leerlo.

la 2da parte del Given parece ser una validación, eso lo podemos meter en un script aparte?

2022-03-30 00:34 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        When select “Discover more music”.
Aqui igual, el nombre de la sección ponlo en español

2022-03-30 00:34 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        And tap on See more and select a playlist from those that appear in the list
A partir de este paso, parece ser otro test script, podemos separarlos para que solo haya una validación por script?

2022-03-30 00:34 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        Then It should be able to play in the background, open another app, and leave BAZ in the background.
Aqui lo mismo que arriba

2022-03-30 00:34 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        Given it should be possible to open and close the banner during the playback of music selected by the user.
Given es usado para definir "pre-requisitos", aquí esto parece una validación, podemos cambiarlo?

2022-03-30 00:34 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        And press the play/pause button
De este paso hacia abajo parecen validaciones adicionales que no corresponden a la principal hecha por el Then.

Si queremos validar mas secciones de esa pantalla lo mas recomendable es tener scripts por separado

2022-03-30 00:34 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        And validate that the music playback control is shown in the notification part,
Cada uno de estos es una validación (then) diferente, podemos separarlos también?

2022-03-30 15:41 UTC, AlanJoseph31 commented on features/Entretenimiento /musica.sec.feature
> +        Given view the Dashboard Diversion
Hola Marco, Entonces en las secciones se pueden usar Comillas?

2022-03-30 15:57 UTC, AlanJoseph31 commented on features/Entretenimiento /musica.sec.feature
> +        Then Validate that the main Dashboard shows the carousel with the content Swipe right
Es un carrusel y la acción que quería decir, era deslizar el carrusel a la derecha

2022-03-30 15:58 UTC, AlanJoseph31 commented on features/Entretenimiento /musica.sec.feature
> +        And tap on See more and select a playlist from those that appear in the list
de acuerdo!

2022-03-30 15:59 UTC, AlanJoseph31 commented on features/Entretenimiento /musica.sec.feature
> +        Given it should be possible to open and close the banner during the playback of music selected by the user.
en ese caso un Then o When cierto?

2022-03-30 16:35 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        Given view the Dashboard Diversion
Si, y en español :P

2022-03-30 16:36 UTC, zoam21 commented on features/Entretenimiento /musica.sec.feature
> +        Then Validate that the main Dashboard shows the carousel with the content Swipe right
Aqui lo podrías poner así: "... by swapping right"

2022-05-02 16:58 UTC, closed without merging