Nazaevan
Atapiave/QA_team pull request #15
Opened 2022-03-16 19:26 UTC by nazaevan

## Any background context you want to provide?

Adding bank_statement.feature and payments.feature

## What does this PR do?

Adds bank_statement.feature and payments.feature

## Where should the reviewer start?

On bank_statement.feature and payments.feature

## How should this be tested?

No testing needed

## What are the relevant tickets?

## Screenshots - Before

## Screenshots - After

## Questions :question:
#### Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2022-03-29 23:24 UTC, zoam21 requested changes
Hay pasos que podemos rehusar en varios de los tests, podemos extraerlos en un método/función que pueda ser rehusado? Saludos!

2022-03-29 23:24 UTC, zoam21 commented on Behave/features/pagos/bank_statement.feature
> +        When select the money option.
Aquí lo mejor es mantener entre comillas el nombre de las opciones, para que una ves que se automatice sean estas las que revisemos en un switch o algo similar. en este caso es "Dinero"?

2022-03-29 23:24 UTC, zoam21 commented on Behave/features/pagos/bank_statement.feature
> +        When select the money option.
En lugar de select pondría "tap" para la acción del usuario

2022-03-29 23:24 UTC, zoam21 commented on Behave/features/pagos/bank_statement.feature
> +        Then we bank statement is displayed.
aqui le agregaría  la palabra "validate", para especificar la acción a realizar

2022-03-29 23:24 UTC, zoam21 commented on Behave/features/pagos/payments.feature
> +        And we tap on 9 more forms from Make it easy with baz section
Lo mismo que arriba, le pondría el nombre de los botones u opciones en español usando comillas

2022-03-29 23:24 UTC, zoam21 commented on Behave/features/pagos/payments.feature
> +
Hay forma de hacer este test mas corto? podemos en el GIVEN meter la pantalla antes a donde se van a hacer las validaciones para evitar poner tanto paso :o

2022-03-29 23:24 UTC, zoam21 commented on Behave/features/pagos/payments.feature
> +
Aqui igual, si te fijas hay varios pasos que se repiten, pudiéramos hacer un método en la pantalla correspondiente para llegar a esa pantalla y rehusaríamos el código

2022-03-29 23:24 UTC, zoam21 commented on Behave/features/pagos/payments.feature
> +
Igual aquí y en los tests posteriores, hay pasos que se repiten entre los tests anteriores

2022-04-04 17:24 UTC, nazaevan commented on Behave/features/pagos/bank_statement.feature
> +        When select the money option.
Claro... lo voy revisando.

2022-04-04 17:24 UTC, nazaevan commented on Behave/features/pagos/bank_statement.feature
> +        Then we bank statement is displayed.
de acuerdo, se fue en un dedazo seguramente.

2022-04-04 17:25 UTC, nazaevan commented on Behave/features/pagos/payments.feature
> +
si, es algo que Daybirth me comentó... pero los chicos del programa como que no estan de acuerdo... Dejame armar una propuesta y ya la paso.

2022-04-04 17:26 UTC, nazaevan commented on Behave/features/pagos/payments.feature
> +
De acuerdo con eso, se podrian resumir en una funcion que pudieramos reutilizar.

2022-04-04 17:26 UTC, nazaevan commented on Behave/features/pagos/payments.feature
> +
de acuerdo, lo reviso Marco. Muchas gracias!

2022-05-02 16:56 UTC, closed without merging