Nazaevanbaseactions
Atapiave/QA_team pull request #27
Opened 2022-04-25 23:33 UTC by nazaevan

## Any background context you want to provide?

Implementing necessary scripts for Scenario: Check Pagos screen sections, from Canal base matrix sheet. 

## What does this PR do?

Implementing the necessary scripts on pagos.tab.feature, Behave/screens/base_actions.py, Behave/screens/canal/pagos_tab.py and Behave/steps/canal/canal_steps.py

## Where should the reviewer start?

In pagos.tab.feature, Behave/screens/base_actions.py, Behave/screens/canal/pagos_tab.py and Behave/steps/canal/canal_steps.py files.

## How should this be tested?

Running the test with the next command: paver run_feature android device_id canal   

## What are the relevant tickets?

Implementing [SUPAUT-9](https://jira.colaboracionsimba.net/browse/SUPAUT-9)

## Screenshots - Before

## Screenshots - After

## Questions :question:
#### Checklist

- [yes] I added the necessary documentation, if appropriate.
- [yes] I added tests to prove that my fix is effective or my feature works.
- [yes] I reviewed existing Pull Requests before submitting mine.

2022-05-02 16:54 UTC, zoam21 requested changes

2022-05-02 16:54 UTC, zoam21 commented on Behave/screens/base_actions.py
> +    def assert_specific_text_element(self, element, value):
"Elemento" que tipo de parametro es?

2022-05-02 16:54 UTC, zoam21 commented on Behave/screens/base_actions.py
> +            element_text = element.text
Aqui se espera que haga la asignación a un que no exista el elemento o el texto?

2022-05-02 16:54 UTC, zoam21 commented on Behave/screens/base_actions.py
> +    def tap_specific_element(self, specific_element):
"specific_element", que tipo de parametro es? 

Cuál es la diferencia entre este metido y el otro que tenemos llamado "tap_element"?

2022-05-02 16:54 UTC, zoam21 commented on Behave/screens/base_actions.py
>          temp_element = self.driver.find_elements(*locator)
el nombre de la variable "temp_element" hay que hacerlo un poco más descriptivo, pudiera ser "element_list" o algo similar

2022-05-02 16:54 UTC, zoam21 commented on Behave/screens/base_actions.py
>          for item in temp_element:
"item" también, si se usará "element_list", lo ideal es usar "element" para que sea mas claro

2022-05-02 16:54 UTC, zoam21 commented on Behave/screens/base_actions.py
>      def swipe_and_tap_element_in_list(self, value, *locator):
Aquí, podemos invertir el orden de los parámetros, por favor? Que primero sea el *locator y luego el value, de la siguiente manera:
"def swipe_and_tap_element_in_list(self, *locator, value):"

Esto ayudará a darle claridad al código al poner primero el elemento a evaluar, y luego el valor de la búsqueda

2022-05-02 16:54 UTC, zoam21 commented on Behave/steps/canal/canal_steps.py
> +    pagos_tab.assert_if_element_is_displayed(*(By.XPATH, "//*[contains(@text,'Haz más con tu dinero')]"))
En este archivo de steps, no deberían existir estos selectores, hay que moverlos al archivo de screen correspondiente y aquí solo se haría la evaluación

2022-05-02 17:13 UTC, nazaevan commented on Behave/screens/base_actions.py
> +    def assert_specific_text_element(self, element, value):
Elemento es  de tipo WebElement, ya es el elemento concreto.

2022-05-02 17:14 UTC, nazaevan commented on Behave/screens/base_actions.py
> +            element_text = element.text
aqui esta mal, no deberia hacer la asignacion, sino mandar el error de que no encontro el elemento. Lo cambio.

2022-05-02 17:14 UTC, nazaevan commented on Behave/screens/base_actions.py
> +    def tap_specific_element(self, specific_element):
el de tap element, recibe una coleccion de elementos y un locator no especifico, y el de tap specific element, lleva el WebElement especifico.

2022-05-02 17:15 UTC, nazaevan commented on Behave/screens/base_actions.py
>          temp_element = self.driver.find_elements(*locator)
De acuerdo, hago el cambio.

2022-05-02 17:15 UTC, nazaevan commented on Behave/screens/base_actions.py
>          for item in temp_element:
De acuerdo, hago el cambio.

2022-05-02 17:16 UTC, nazaevan commented on Behave/screens/base_actions.py
>                  actions.move_to_element(element).perform()
Hago la prueba y te aviso.

2022-05-02 17:16 UTC, nazaevan commented on Behave/screens/base_actions.py
>      def swipe_and_tap_element_in_list(self, value, *locator):
De acuerdo, hago el cambio.

2022-05-02 17:16 UTC, nazaevan commented on Behave/steps/canal/canal_steps.py
> +    pagos_tab.assert_if_element_is_displayed(*(By.XPATH, "//*[contains(@text,'Haz más con tu dinero')]"))
De acuerdo, hago el cambio.

2022-05-02 17:55 UTC, zoam21 requested changes

2022-05-02 17:55 UTC, zoam21 commented on Behave/screens/canal/pagos_tab.py
> +            self.btn_ver_mas_operaciones = self.get_element_in_list("Ver más operaciones", *(By.CLASS_NAME, "android.view.View"))
Para estos selectores, no sería mejor usar XPATHs relativos? Para de esa forma usar los métodos que creamos para hacer los scrolls

2022-05-02 17:58 UTC, nazaevan commented on Behave/screens/canal/pagos_tab.py
> +            self.btn_ver_mas_operaciones = self.get_element_in_list("Ver más operaciones", *(By.CLASS_NAME, "android.view.View"))
mmm podria ser, aunque como ya estan visibles en la pantalla, no seria necesario hacer scroll.

2022-05-02 17:59 UTC, nazaevan commented on Behave/screens/canal/pagos_tab.py
> +            self.btn_ver_mas_operaciones = self.get_element_in_list("Ver más operaciones", *(By.CLASS_NAME, "android.view.View"))
O que opinas, los cambiamos con los xpath relativos?

2022-05-02 18:00 UTC, zoam21 commented on Behave/screens/canal/pagos_tab.py
> +            self.btn_ver_mas_operaciones = self.get_element_in_list("Ver más operaciones", *(By.CLASS_NAME, "android.view.View"))
Si, se me hace un poco mas limpio, ya si se ejecuta en un teléfono mas pequeño no tendremos problema para encontrarlos en el futuro

2022-05-03 18:28 UTC, nazaevan commented on Behave/screens/base_actions.py
> +            element_text = element.text
En el ultimo push, este metodo se comento.

2022-05-03 18:29 UTC, nazaevan commented on Behave/screens/base_actions.py
> +    def tap_specific_element(self, specific_element):
en el ultimo push, este metodo se comento.

2022-05-03 18:30 UTC, nazaevan commented on Behave/screens/base_actions.py
>          temp_element = self.driver.find_elements(*locator)
queda como element_list, hecho en el ultimo push.

2022-05-03 18:31 UTC, nazaevan commented on Behave/screens/base_actions.py
>          for item in temp_element:
queda como current_element, en el ultimo push.

2022-05-03 18:36 UTC, nazaevan commented on Behave/screens/base_actions.py
>                  actions.move_to_element(element).perform()
Ya revise, y no uso este metodo en alguna de mis pruebas... seguro fue un cambio que meti con copy paste del codigo de Yanira, voy a dejar la funcion tal cual esta en main y si hay cambio, que se revise en su momento.

2022-05-03 18:38 UTC, nazaevan commented on Behave/steps/canal/canal_steps.py
> +    pagos_tab.assert_if_element_is_displayed(*(By.XPATH, "//*[contains(@text,'Haz más con tu dinero')]"))
Se aplica el cambio en el ultimo push.

2022-05-03 18:38 UTC, nazaevan commented on Behave/screens/canal/pagos_tab.py
> +            self.btn_ver_mas_operaciones = self.get_element_in_list("Ver más operaciones", *(By.CLASS_NAME, "android.view.View"))
Se hace el cambio en el ultimo push.

2022-05-03 19:05 UTC, nazaevan commented on Behave/screens/base_actions.py
>      def swipe_and_tap_element_in_list(self, value, *locator):
listo en el ultimo push

2022-05-03 22:21 UTC, zoam21 approved these changes
Gracias por el excelente trabajo! 

🚀

2022-05-03 22:22 UTC, merged