TwoTestCases
Atapiave/QA_team pull request #30
Opened 2022-05-03 15:41 UTC by JRubio07

First and second automated test cases

## Any background context you want to provide?

## What does this PR do?

## Where should the reviewer start?

## How should this be tested?

## What are the relevant tickets?

## Screenshots - Before

## Screenshots - After

## Questions :question:
#### Checklist

- [ ] I added the necessary documentation, if appropriate.
- [ ] I added tests to prove that my fix is effective or my feature works.
- [ ] I reviewed existing Pull Requests before submitting mine.

2022-05-03 15:49 UTC, zoam21 requested changes
Me puedes ayudar a agregar la descripción del PR por favor? 😄

2022-05-03 17:14 UTC, JRubio07 commented
> Me puedes ayudar a agregar la descripción del PR por favor? 😄
Listo!

2022-05-03 22:00 UTC, zoam21 requested changes
Muy buen trabajo!

Hay algunas correcciones y clarificaciones, me pueden ayudar con eso?

Saludos!

2022-05-03 22:27 UTC, JRubio07 commented on Behave/features/nuevas_iniciativas/portabilidad.feature
> +    When identify the "Pasa tu nómina con nosotros" card
Haré el cambio de card a banner para que sea más entendible y lo que el usuario espera ver es ese banner

2022-05-03 22:29 UTC, JRubio07 commented on Behave/features/nuevas_iniciativas/portabilidad.feature
> +    Then we verify screen benefit
En este caso, solamente nos encargamos de verificar que la pantalla de portabilidad se pueda acceder y así poder visualizar los beneficios

2022-05-03 22:31 UTC, JRubio07 commented on Behave/screens/canal/pagos_tab.py
> +                                        "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.vi
El detalle es que los textos del banner no son clickable entonces se necesita del banner como tal para realizar el click

2022-05-03 22:33 UTC, zoam21 commented on Behave/screens/canal/pagos_tab.py
> +                                        "/hierarchy/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.widget.LinearLayout/android.widget.FrameLayout/android.vi
¿No aparecen dentro de las caracteristicas/propiedades del elemento? o son solamente textos en una imagen?

2022-05-05 20:59 UTC, zoam21 requested changes
Solo unos cambios menores

2022-05-05 20:59 UTC, zoam21 commented on Behave/screens/canal/pagos_tab.py
> +            self.lbl_subTitle = (By.XPATH, "//*[contains(@text,'Puedes solicitar un crédito inmediato desde $1,000.')]")
El nombre de la variable que contiene a estos 2 selectores hay que hacerlo mas especifico, puede ser algo como: 

self.lbl_title_nomina_con_nosotros

o algo similar.

Lo mismo para el subtitulo

2022-05-05 20:59 UTC, zoam21 commented on Behave/screens/nuevas_iniciativas/portabilidad_screen.py
> +        self.platform = platform
Esta línea ya no es necesaria, ¿la podemos remover, por favor?

2022-05-09 21:58 UTC, zoam21 approved these changes
Gracias por el excelente trabajo!

2022-05-09 21:59 UTC, merged