Pagos/ianarie
Atapiave/QA_team pull request #31
Opened 2022-05-03 17:27 UTC by ianarie

Baz Payments to Azteca Bank

## Any background context you want to provide?
Scripts are required to test payments from baz to azteca bank

## What does this PR do?
Scripts to test baz payments to Azteca Bank, logged in flag, rename files.

## Where should the reviewer start?
\QA_team\Behave\features\pagos\payments_to_azteca_bank.feature
\QA_team\Behave\screens\pagos\payments_to_azteca_bank_screen.py
\QA_team\Behave\steps\pagos\payments_to_azteca_bank_steps.py
\QA_team\Behave\environment.py

## How should this be tested?
In terminal 
paver run_feature android 200c0c8a pagos

## What are the relevant tickets?
https://jira.colaboracionsimba.net/browse/SUPAUT-16

2022-05-03 20:01 UTC, zoam21 requested changes
Excelente trabajo!

Solo unos cambios menores, me puedes ayudar a hacerlos?

Saludos!

2022-05-03 20:01 UTC, zoam21 commented on Behave/steps/pagos/payments_to_azteca_bank_steps.py
> +    paymentsMobileAccount_screen = PaymentsAztecaBankScreen(
Mismo comentario aqui con el estándar para la definición de los nombres de variables que arriba

2022-05-03 20:01 UTC, zoam21 commented on Behave/steps/pagos/payments_to_azteca_bank_steps.py
> +    paymentsMobileAccount_screen = PaymentsAztecaBankScreen(
Mismo comentario aqui con el estándar para la definición de los nombres de variables que arriba

2022-05-03 20:01 UTC, zoam21 commented on Behave/steps/pagos/payments_to_azteca_bank_steps.py
> +    paymentsMobileAccount_screen = PaymentsAztecaBankScreen(
Mismo comentario aqui con el estándar para la definición de los nombres de variables que arriba

2022-05-04 15:40 UTC, ianarie commented
Cambios realizados

2022-05-04 17:01 UTC, zoam21 approved these changes
Excelente trabajo!

🚀

2022-05-04 17:01 UTC, merged