Create mis_compras_cancelacion.feature
Atapiave/QA_team pull request #8
Opened 2022-03-02 14:57 UTC by Chalvizo

validate the display of cancelation

2022-03-03 15:54 UTC, Atapiave requested changes
No estamos usando correctamente las keywords, When se ocupa cuando hay una acción simple y Then se ocupa cuando hay un output que se puede validar o verificar, además no se intercalan, si se sigue utilizando la misma keyword solo se continua con And hasta que la keyword cambie

2022-03-30 18:10 UTC, zoam21 requested changes
¿Nos puedes ayudar a separar este buen test en varios?

Cualquier duda, con gusto te puedo ayudar 😃

2022-03-30 18:10 UTC, zoam21 commented on features/compras/mis_compras_cancelacion.feature
> +        Then show the order history screen (Mis pedidos)
Hasta aquí terminaría el primer test

2022-03-30 18:10 UTC, zoam21 commented on features/compras/mis_compras_cancelacion.feature
> +        Then the Detalle de la compra screen will be displayed.
Estos 2 pasos serían otro test case, necesitaríamos agregar un Given

2022-03-30 18:10 UTC, zoam21 commented on features/compras/mis_compras_cancelacion.feature
> +        Then the Detalle de la compra screen will be displayed.
Estos 2 pasos serían otro test case, necesitaríamos agregar un Given

2022-03-30 18:10 UTC, zoam21 commented on features/compras/mis_compras_cancelacion.feature
> +        Then the "Cancelar pedido" screen will be displayed (Form to request the cancellation).
Como lo dice Arturo, 
**Given**: lo podemos usar para definir el test case.
**When**: sería para las acciones simples
**Then**: para indicar las validaciones

Este test pudiera ser así:

_Given_ the user wants to cancel an order
_When_ the user taps into the "Cancelar pedido" button
_And_ confirms the action
_Then_ the "Cancelar pedido" screen will be displayed

2022-03-30 18:10 UTC, zoam21 commented on features/compras/mis_compras_cancelacion.feature
> +        Then the "Cancelar pedido" screen will be displayed (Form to request the cancellation).
Como lo dice Arturo, 
**Given**: lo podemos usar para definir el test case.
**When**: sería para las acciones simples
**Then**: para indicar las validaciones

Este test pudiera ser así:

_Given_ the user wants to cancel an order
_When_ the user taps into the "Cancelar pedido" button
_And_ confirms the action
_Then_ the "Cancelar pedido" screen will be displayed

2022-05-02 17:02 UTC, closed without merging